name: 🔧 Chore / Maintenance
description: Request refactoring, cleanup, or maintenance task
labels: ["claude-implement", "type:chore"]
body:
  - type: markdown
    attributes:
      value: |
        ## Chore / Maintenance Task
        Describe the maintenance task for Claude Code.
        
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A one-line summary of the task
      placeholder: "Refactor user authentication module"
    validations:
      required: true
      
  - type: dropdown
    id: chore_type
    attributes:
      label: Type of Chore
      options:
        - Refactor - Improve code structure without changing behavior
        - Cleanup - Remove dead code, fix formatting, organize imports
        - Update - Update dependencies or configurations
        - Documentation - Add or update documentation
        - Testing - Add or improve test coverage
        - Performance - Optimize performance
        - Security - Fix security issues or improve security
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done and why?
      placeholder: |
        The authentication module has grown too large and is hard to maintain.
        We need to split it into smaller, focused modules:
        - Auth provider
        - Session management  
        - Token handling
    validations:
      required: true
      
  - type: textarea
    id: files
    attributes:
      label: Files/Areas Affected
      description: Which files or areas of the codebase need work?
      placeholder: |
        - src/auth/index.ts (main file to split)
        - src/auth/middleware.ts
        - src/utils/jwt.ts
    validations:
      required: true
      
  - type: textarea
    id: constraints
    attributes:
      label: Constraints (Optional)
      description: Any constraints or requirements to follow?
      placeholder: |
        - Don't change the public API
        - Maintain backward compatibility
        - All existing tests must pass
